language: javascript
sudo: false
before_script:
  - npm install -g casperjs
script: 
  - casperjs test test/tests_sync.js
  - casperjs test test/tests_async.js
  - casperjs test test/tests_helpers.js
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "m+1utDjApM92lBHF9BBGdk5w64e8NhHnY+AwJtef9CdhrR8gC3KZ1bj7J5D+ZaUxDQL/99hbw/rS/+FVaiLY/9P1wHDMUoKtkVOrHUZZ8ERWzht6lLMKygl54jJmDIXXWPwG691qsKWx8C/r7Rx4gwflbncmWV1AVYnP8O822P4="

addons:
  coverity_scan:
    project:
      name: "Countly/countly-sdk-web"
    notification_email: ar2rsawseen@yahoo.com
    build_command_prepend: ""
    build_command:
      - casperjs test test/tests_sync.js
      - casperjs test test/tests_async.js
      - casperjs test test/tests_helpers.js
    branch_pattern: master