language: node_js
node_js:
  - "6"
sudo: false
branches:
  except:
  - gh-pages
env:
  global:
  - GH_REPO_NAME: countly-sdk-web
  - GH_REPO_REF: github.com/Countly/countly-sdk-web.git
  - secure: ONfNUHKLNXeG+mqPucbNhXnw7VRmpYKJDXLxyyO1ZxyoSZLytDH9QD3xXLLKwfqVP1DfEAI26xwipGAZejvaXB5Td+a4Q+b3B0Wx0q3kYSh+oQL/CK16HrJkeAbe68hXIYTdRMzQkbwTgDlRbmJiMoNOS6tos6H5dq7V/j5ND60=
before_script:
- npm install
- npm install -g casperjs
- npm install -g jshint
script:
- jshint lib/countly.js
- casperjs test test/tests_sync.js
- casperjs test test/tests_async.js
- casperjs test test/tests_helpers.js
after_success:
- cd $TRAVIS_BUILD_DIR
- chmod +x generateDocs.sh
- bash generateDocs.sh
